### PR TITLE
update simulator to 367eec2 (Fix macOS install script)

### PR DESCRIPTION
**Pull request by Adimote**

### CODE REVIEW

**Comment by trickeydan** [comment]
Is there anything blocking the merge of this? @Adimote 

It would be nice to deploy this to teams.

**Comment by PeterJCLaw** [comment]
I recall that someone tried this (maybe discussed in Slack?) and while it fixed one problem, there was another issue it uncovered.

**Comment by PeterJCLaw** [comment]
> I recall that someone tried this (maybe discussed in Slack?) and while it fixed one problem, there was another issue it uncovered.

Scratch that, I can't find a reference to this.

**Comment by trickeydan** [comment]
We have a team asking about this on the forum.

I'd like to merge it please.

**Comment by Adimote** [comment]
derp forgot to click merge

**Pull request merged**
