### PR TITLE
Bring docs within style guide

### PR DESCRIPTION
**Pull request by jimmythompson**
This is a first cut at bringing the documentation in line with the style guide , and with the rest of the website, as raised in #2.

screen shot 2016-09-11 at 13 32 53

Some problems:

* the syntax highlighting is still inconsistent,
* there's a bunch of missing images, and
* the sidebar is manually created.

### CODE REVIEW

**Comment by jimmythompson** [comment]
There's also a number of visual inconsistencies, like this one:

screen shot 2016-09-11 at 13 39 22

**Comment by PeterJCLaw** [comment]
Why has the IDE folder been renamed here? This doesn't really make sense as "IDE" is an acronym and thus should be capitalised.

**Comment by PeterJCLaw** [comment]
I don't think that we should merge a manually created sidebar as having it will remove the impetus to replace it with an auto-generated one (which is the right solution).

**Comment by rspanton** [comment]
Awesome Jimmy -- thanks for investing some time in this.

**Pull request merged**
