### PR TITLE
Update code instructions for removal of robot.zips

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This year we've moved to just running the code directly on the USB stick, without a robot.zip wrapper.

I've eyeballed the menus on macOS, I'm relying on memory for what they're called on Windows.

Fixes https://github.com/srobo/docs/issues/344

### CODE REVIEW

**Review by antoinepetty — APPROVED** [review]
Feels quite basic but it is correct for Windows

**Review by trickeydan — APPROVED** [review]
At a later date we can document how to change the entrypoint, although this is good for now.

**Comment by raccube** [comment]
A couple things:
- The context menus on Windows 11 are a bit different now. I'll get you a screenshot later.
- I'm going to merge in the browser interface soon so that note on restarting code will need to be updated.

**Comment by PeterJCLaw** [comment]
> * The context menus on Windows 11 are a bit different now. I'll get you a screenshot later.

Ah, ok. Thanks.

> * I'm going to merge in the browser interface soon so that note on restarting code will need to be updated.

Oh, is auto-restarting no longer going to be a thing?

**Pull request merged**
