### PR TITLE
Update SR2023 markers

### PR DESCRIPTION
**Pull request by sedders123**
Changes to the new sizes and the colour of the border from black to grey

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Meta: it's useful when updating binaries like this to cross reference where the binary came from -- this makes for easier review as well as making it easier to update (if the commit message includes the instructions to regenerate).

**Comment by sedders123** [comment]
👍 Binary came from https://github.com/srobo/game-markers/commit/7dcca296a1196a25296ef7a29455faf287671e41

**Comment by PeterJCLaw** [comment]
Hrm, the contents of the zip seem to be different than the SR2023 files in the linked commit.

**Comment by PeterJCLaw** [comment]
Ah, that seems to be an inconsistency within the game-markers repo.

**Comment by sedders123** [comment]
That's odd I did diff locally and they were identical, I have also just copied the ZIP from game-markers to docs and there is no diff

**Comment by PeterJCLaw** [comment]
Sorry: the zip file here and in the game-markers repos are the same. The zip contains different files than are in the `markers` folder in the game-markers repo (i.e: the game-markers repo is internally inconsistent).

**Comment by PeterJCLaw** [comment]
Looks like the repo got out of step at 341b9a51b6a8f6af36fa5bb725b61ce3683d7946

**Review by PeterJCLaw — APPROVED** [review]

**Pull request merged**
