### PR TITLE
Document the Servo Board control scheme and specifications

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Fixes https://github.com/srobo/docs/issues/101 (from which it also draws its information).

Reviewer: please consider whether the terminology here is useful/correct; I've essentially made it up as I don't know what to call this.

### CODE REVIEW

**Review by WillB97 — COMMENTED** [review]
Seems good, just needs the acronyms corrected

**Comment by richardbarlow** [comment]
I feel that using the term PWM for hobby servo control signals is a bit misleading. PWM is generally used to indicate a fixed frequency signal with varying duty cycle. The hobby servo control signal consists of controlled on duration and (mostly) uncontrolled off duration. Therefore it's not a fixed frequency or duty cycle for a given position. It might be more clear to refer to these values as 'Servo control pulse range' and 'Servo control pulse resolution'.

In addition, it would be good to indicate the other timing properties of the signal such as min/max repetition rate. This range is a function of all servo output signals, but it shouldn't be too hard to determine min/max from code inspection.

**Comment by WillB97** [comment]
I agree, something around servo pulse range is a better name.

**Comment by richardbarlow** [comment]
I've just read the code (I didn't leave myself many hints!). I have determined that the minimum overall repetition period is 16.825ms (59.435Hz) and the maximum is 17.825ms (56.101Hz). These are the worst case values for the complete round of 12 pulses, regardless of what combination of servo positions are being output.

However, since the pulses are not always output in the same order each round (see below), the actual observed worse case for a single output needs to take into account a servo going from being the shortest to the longest pulse (which could happen even if that servos position isn't itself changed - all of the other servo positions might have been changed).

If it went from being longest (last output) to shortest (first output) and assuming that it's set to the shortest pulse duration then its repetition rate will be 16.075ms. If it went from shortest to longest and assuming it's set to the longest pulse duration then its repetition rate will be 18.575ms.

Based on all this you could state that the worst case repetition rate values that a single servo will experience are:

Minimum: 16.075ms (62.208Hz)
Maximum: 18.575ms (53.836Hz)

The actual value is very much dependent on the pulse durations of all of the other outputs, but this should not matter at all to the servo. Hence why it's not PWM in the usual sense.

--- 

The reason for the above complexity is due to how the servo board outputs its pulses: The firmware first sorts its output pulses from shortest to longest and then outputs them in a staggered manner. It then sets each output high with a small fixed delay between each output (75us) and finally turns them off one at a time after the necessary delay. Since they were sorted shortest to longest, there is always at least 75us between any required state change. This prevents any interaction between servo outputs - there should be no jitter. The whole process repeats (including the sorting) for each round of pulses.

**Comment by PeterJCLaw** [comment]
Thanks for those details @richardbarlow :)

I've added a new section to the docs to include some of this as background (which I suspect will be useful for everyone) and updated the specifications table with the naming and details as suggested.

Would be great to check if what I've put is both accurate as well as understandable by a lay reader.

**Review by richardbarlow — APPROVED** [review]
LGTM. Perhaps if I get a chance at some point I'll make a timing diagram explaining all of this more clearly and it can live next to the firmware

**Pull request merged**
