### PR TITLE
Lists start from one

### PR DESCRIPTION
**Pull request by WillB97**
People count from one, so should our lists.

### CODE REVIEW

**Review by PeterJCLaw — CHANGES_REQUESTED** [review]
These lists starting from 0 is intentional -- it's somewhat assumed that people may have already cloned the repo if they're reading the setup instructions.

**Comment by WillB97** [comment]
> These lists starting from 0 is intentional -- it's somewhat assumed that people may have already cloned the repo if they're reading the setup instructions.

Then they just skip over the step it doesn't remove the fact that the step exists.

**Review by PeterJCLaw — APPROVED** [review]

**Comment by RealOrangeOne** [comment]
If we're going to make this change, I'd suggest actually renumbering the markdown source so the numbers are sequential.

**Comment by PeterJCLaw** [comment]
> If we're going to make this change, I'd suggest actually renumbering the markdown source so the numbers are sequential.

I'd actually suggest going the other way -- make them all `1.` so that there's no redundant diff when changes are made. https://github.com/srobo/docs/pull/585 actually does that as it was doing some other related tidying.

**Pull request merged**
